name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: '0 */24 * * *' # Executa uma vez por dia (à meia-noite UTC)
  workflow_dispatch: # Permite executar manualmente pela aba Actions
  push:
    branches:
      - main # Executa em pushes na branch principal (você pode ajustar)

jobs:
  generate:
    permissions:
      contents: write # Permite que o workflow escreva no repositório
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Gabautista 

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Atualizar gráfico de contribuições Pac-Man'
          file_pattern: pacman-contribution-graph.svg
